---
version: '3.7'
services:
  turn:
    image: scopear/docker-turnserver:on-prem-2.13.2
    networks:
    - outside
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 0s
        failure_action: rollback
        order: stop-first
      rollback_config:
        parallelism: 0
        delay: 0s
        failure_action: pause
        order: stop-first
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '5'
    env_file:
    - turn.env
  nginx:
    image: scopear/docker-nginx:on-prem-2.13.2
    ports:
    - 8030:8000
    networks: []
    secrets: []
    deploy:
      update_config:
        parallelism: 1
        delay: 0s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 0
        delay: 0s
        failure_action: pause
        order: start-first
      replicas: 1
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '5'
    volumes: []
    env_file:
    - nginx_proxy.env
#  tunnel:
#    image: scopear/docker-tunnel:on-prem-2.13.2
#    ports:
#    - 8443:443
#    networks: []
#    secrets: []
#    deploy:
#      update_config:
#        parallelism: 1
#        delay: 0s
#        failure_action: rollback
#        order: start-first
#      rollback_config:
#        parallelism: 0
#        delay: 0s
#        failure_action: pause
#        order: start-first
#      replicas: 1
#    logging:
#      driver: json-file
#      options:
#        max-size: 100m
#        max-file: '5'
#    volumes: []
networks:
  default:
    driver: overlay
    ipam:
      config:
      - subnet: 172.24.0.0/16
  outside:
    name: swarm1
    external: false
secrets: {}
